### ISSUE TITLE
Compile under ubuntu

### ISSUE THREAD

**Issue by pgouv** [rsa9000/npk-tools#1]
Although I installed zlib1g-dev I am getting now undefined reference to `inflateInit_` ... etc 
Any solution ?

**Comment by rsa9000** [comment]
Just check with Debian Jessie x64 with installed zlib1g-dev-1.2.8 and npk-tools compiled successfully.

You could try to check, which linking options is recommended (via pkg-config) and then correct Makefile:
pkg-config --libs libz

**Comment by pgouv** [comment]
thank you. I just added -lz at the end and it compiled.
However when tried extracting I was always getting "Error: remain file chunk not enogh for partition"
Which versions does it support?

**Comment by rsa9000** [comment]
It supports old versions. I personally use it with ROSv5. With ROSv6 it works not so good.

**Comment by pgouv** [comment]
Hm nice. Does these file contain executables etc? Are all these written in C?

**Comment by rsa9000** [comment]
What file do you mean? If you mean MikroTik packages (with *.npk extension), then the answer is yes. They are contain executables/libraries/drivers. RouterOS is just some kind of Linux distributive with a lot of proprietary code.

**Comment by rsa9000** [comment]
And yes this files are mostly binary and written in compilable languages (e.g. C, C++, etc.) So, even when you extract them, you can not easily audit them.

**Comment by rsa9000** [comment]
Compilation issue is solved, and after latest changes in source code the unpacking of newer versions of NPK files is supported too, so I close this issue. Feel free to open new issue if something going not as expected.
