### ISSUE TITLE
Managed to compile under Mingw but unable to extraxt latest lcd npk file

### ISSUE THREAD

**Issue by veso266** [rsa9000/npk-tools#2]
Hi there I managed to compile this under windows: https://github.com/veso266/npk-tools/commit/7d525ad71ce628559827c0ecee7a0b2150251838
(yea windows doesn't have gmtime_r and I didn't reimplement it so no timestamp :cry: )

but when trying to open a recent npk package: https://github.com/veso266/npk-tools/blob/master/routeros-mipsbe-6.44.5.npk
it doesn't want to extraxt partition data for some reason
file format should stay the same according to: https://kirils.org/slides/2017-08-06_prez_SHA_MT_pub.pdf
slide 31-36
when trying to get the dump: ./unnpk.exe -tvvf routeros-mipsbe-6.44.5.npk
[Partition header]
Type: 18 (Main package information)
Size: 1869742080
Error: remain file chunk not enogh for partition data.

it gets the header fine but file chunk is not long
now as crazy as it sounds, could this be windows issue and it works fine on linux?

Thanks for Anwsering and Best Regards

**Comment by rsa9000** [comment]
I check the package on a *nix system. Everything works as expected:

```
$ sha1sum routeros-mipsbe-6.44.5.npk 
d17b873ee4c8e36f5ba5e61edd19b1a1388908e8  routeros-mipsbe-6.44.5.npk
$ unnpk -tvf routeros-mipsbe-6.44.5.npk | head -n 14

[Main header]
Signature : hex:1E F1 D0 BA
Remain siz: 11933340

[Partition header]
Type: 18 (Main package information)
Size: 32
Name      : routeros-mipsbe
Unknown   : hex:66
Version   : 6.44.5
Timestamp : 1562236341 (Thu Jul  4 10:32:21 2019)
Unknown   : hex:00 00 00 00 00 00 00 00

$ mkdir routeros-mipsbe-6.44.5
$ unnpk -xvf routeros-mipsbe-6.44.5.npk -C routeros-mipsbe-6.44.5
routeros-mipsbe.squashfs
system.squashfs
UPGRADED
bin/bash
boot/
boot/kernel
/var/pdb/system/crc
ipv6.squashfs
wireless@.squashfs
hotspot.squashfs
mpls.squashfs
routing.squashfs
ppp.squashfs
dhcp.squashfs
security.squashfs
advanced-tools.squashfs
$ ls -l routeros-mipsbe-6.44.5
total 10364
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 advanced-tools.squashfs
drwxr-xr-x 2 rsa9000 rsa9000       60 окт 17 14:22 bin
drwxr-xr-x 2 rsa9000 rsa9000       60 окт 17 14:22 boot
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 dhcp.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 hotspot.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 ipv6.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 mpls.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 ppp.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 routeros-mipsbe.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 routing.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 security.squashfs
-rw-r--r-- 1 rsa9000 rsa9000 10612736 окт 17 14:22 system.squashfs
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 UPGRADED
drwxr-xr-x 3 rsa9000 rsa9000       60 окт 17 14:22 var
-rw-r--r-- 1 rsa9000 rsa9000        0 окт 17 14:22 wireless@.squashfs
```

I create a headers dumps of the package with `unnpk -tvf` for your reference: [routeros-mipsbe-6.44.5-content.txt](https://github.com/rsa9000/npk-tools/files/3738984/routeros-mipsbe-6.44.5-content.txt)
